apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: xray-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators-snapshot-xraylab
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v3.5.0

