apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./odh/odh-application.yaml
  - ./openshift-gitops/openshift-gitops-application.yaml
  - ./openshift-operators/openshift-operators-application.yaml
  - ./openshift-serverless/openshift-serverless-application.yaml
  - ./openshift-storage/openshift-storage-application.yaml
  - ./xray-demo/common/common-application.yaml
  - ./xray-demo/kafka/kafka-application.yaml
  - ./xray-demo/helper-db/helper-db-application.yaml
  - ./xray-demo/bucket-helper/bucket-helper-application.yaml
  - ./xray-demo/image-server/image-server-application.yaml
