apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
bases:
  - https://github.com/cgfulton/gitops/odh?ref=gitops
  - https://github.com/cgfulton/gitops/xray-demo?ref=gitops
