---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  finalizers:
    - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: openshift-storage
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ocs-operator
  namespace: openshift-storage
spec:
  channel: stable-4.6
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ocs-operator.v4.6.3
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ocs-storagecluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  manageNodes: false
  resources:
    mon:
      requests:
        cpu: 1
        memory: 2Gi
    mds:
      requests:
        cpu: 3
        memory: 8Gi
    mgr:
      requests:
        cpu: 1
        memory: 3Gi
    noobaa-core:
      requests:
        cpu: 1
        memory: 4Gi
    noobaa-db:
      requests:
        cpu: 1
        memory: 4Gi
  storageDeviceSets:
    - name: ocs-deviceset
      count: 1
      replica: 3
      resources:
        requests:
          cpu: 2
          memory: 5Gi
      placement: {}
      dataPVCTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          volumeMode: Block
          resources:
            requests:
              storage: 2Ti
      portable: true