apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: anonymized-images
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
