apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- common-serverless-operator.yaml
- ocs-subscription.yaml
- odh-subscription.yaml
- openshift-gitops-subscription.yaml
- subscriptions-application.yaml
