apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kogito-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: 1.x
  installPlanApproval: Automatic
  name: kogito-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kogito-operator.v1.2.0
