---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - kubernetes.io/pvc-protection
  name: ocs-storagecluster-ceph-rbd
  namespace: openshift-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - kubernetes.io/pvc-protection
  name: ocs-deviceset
  namespace: openshift-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: gp2
  volumeMode: Block
