apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage # {{ ocp4_workload_rhtr_xraylab_ocs_namespace }}
  name: ocs-storagecluster
spec:
  manageNodes: false
  resources:
    mon:
      requests:
        cpu: 1 # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_mon_cpu }}
        memory: 2Gi # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_mon_mem }}
    mds:
      requests:
        cpu: 3 # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_mds_cpu }}
        memory: 8Gi # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_mds_mem }}
    mgr:
      requests:
        cpu: 1 # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_mgr_cpu }}
        memory: 3Gi # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_mgr_mem }}
    noobaa-core:
      requests:
        cpu: 1 # {{ ocp4_workload_rhtr_xraylab_ocs_mcg_core_cpu }}
        memory: 4Gi # {{ ocp4_workload_rhtr_xraylab_ocs_mcg_core_mem }}
    noobaa-db:
      requests:
        cpu: 1 # {{ ocp4_workload_rhtr_xraylab_ocs_mcg_db_cpu }}
        memory: 4Gi # {{ ocp4_workload_rhtr_xraylab_ocs_mcg_db_mem }}
  storageDeviceSets:
  - name: ocs-deviceset
    count: 1
    replica: 3
    resources:
      requests:
        cpu: 2 # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_osd_cpu }}
        memory: 5Gi # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_osd_mem }}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp2 # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_storage_class_name }}
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 2Ti # {{ ocp4_workload_rhtr_xraylab_ocs_ceph_storage_osd_size }}
    portable: true
