kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-operator
  namespace: xray-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: xray-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-operator