apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: risk-assessment
  namespace: xray-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/guimou/xraylab-risk-assessment:rhtr_v1.4'
      importPolicy: {}
      referencePolicy:
        type: Source
