---
apiVersion: v1
kind: Namespace
metadata:
  name: odh
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  creationTimestamp: '2021-03-11T04:46:10Z'
  finalizers:
    - argoproj.io/finalizer
  generation: 2
  name: argocd-odh
  namespace: odh
  resourceVersion: '166565'
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/odh/argocds/argocd-odh
  uid: 85832d4b-cd8e-4d23-bc22-a2346322511f
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  rbac: {}
  repo: {}
  dex: {}
  ha:
    enabled: false
  tls:
    ca: {}
  redis: {}
  controller:
    processors: {}
status:
  applicationController: Running
  dex: Unknown
  phase: Available
  redis: Running
  repo: Running
  server: Running
