resources:
- amq-streams-openshift-storage-subscription.yaml
- kogito-openshift-storage-subscription.yaml
- odh-openshift-storage-subscription.yaml
- strimzi-kafka-operator-openshift-storage-subscription.yaml
