---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xray-demo-common
  namespace: openshift-gitopts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: xray-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: xray-demo/common/enabled
    repoURL: https://github.com/cgfulton/gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true