---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xray-demo
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: overlays/4.7/xray-demo
    repoURL: https://github.com/cgfulton/gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true