apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: xray-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
    database-user: xraylab
    database-password: xraylab
    database-root-password: xraylab
    database-host: xraylabdb
    database-db: xraylabdb
