kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xraylabdb
  namespace: xray-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
