apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: bucket-helper
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/troyer/bucket-helper:1.0'
      importPolicy: {}
      referencePolicy:
        type: Source
