kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: bucket-helper
  namespace: xray-demo
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'bucket-helper:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.6'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/strangiato/bucket-helper.git'
      ref: main
    contextDir: /bucket-helper
  triggers:
    - type: ImageChange
      imageChange:
    - type: ConfigChange
  runPolicy: Serial
