kind: Service
apiVersion: v1
metadata:
  name: xraylabdb
  namespace: xray-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: xraylabdb
