apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  namespace: openshift-storage
  ownerReferences:
    - apiVersion: noobaa.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: NooBaa
      name: noobaa
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
spec:
  awsS3:
    region: us-east-2
    secret:
      name: noobaa-aws-cloud-creds-secret
      namespace: openshift-storage