---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage # {{ ocp4_workload_rhtr_xraylab_ocs_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  finalizers:
    - kubernetes